services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:15
    container_name: postgres-healthflow
    environment:
      POSTGRES_DB: healthflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_healthflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d healthflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  proxyfhir:
    build: ./proxyfhirservice
    container_name: proxyfhir
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/healthflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      FHIR_SERVER_BASE_URL: https://hapi.fhir.org/baseR4

  deidentification:
    build: ./deidentification-service
    container_name: deidentification
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: postgres
      POSTGRES_DB: healthflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  featurizer:
    build: ./featurizer
    container_name: featurizer
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: postgres
      POSTGRES_DB: healthflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always


  modelrisque:
    build: ./modelrisque
    container_name: modelrisque
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: postgres
      POSTGRES_DB: healthflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TRAIN_MODE: "false"   # ðŸ”´ OBLIGATOIRE
    volumes:
      - ./modelrisque/model:/app/model
    restart: always         # âœ… recommandÃ©

  scoreapi:
    build: ./scoreapi
    container_name: scoreapi
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: postgres
      POSTGRES_DB: healthflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_SECRET_KEY: super-secret-key
    ports:
      - "8002:8000"
    restart: always
  auditfairness:
    build: ./AUDITFAIRNESS
    container_name: auditfairness
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: postgres
      POSTGRES_DB: healthflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PORT: 8050
      REPORTS_DIR: /app/reports
    ports:
      - "8050:8050"
    depends_on:
      - postgres
      - kafka




volumes:
  postgres_healthflow_data:
